version: '3.8'

services:
  api:
    build: .
    container_name: rlaas_api
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped

    env_file: .env
    environment:
      # App config
      APP_ENV:        ${APP_ENV}
      PORT:           ${PORT}

      # Postgres (RDS)
      DATABASE_URL:   ${DATABASE_URL}

      # Rate limiting & RedisCloud
      SHARDING_STRATEGY: ${SHARDING_STRATEGY}
      REDIS_NODE_1:      ${REDISCLOUD_URL}

      # OAuth & JWT
      GOOGLE_CLIENT_ID:     ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OAUTH_REDIRECT_URL:   ${OAUTH_REDIRECT_URL}
      JWT_SECRET:           ${JWT_SECRET}

      # Migrations
      MIGRATE_ON_START: ${MIGRATE_ON_START}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://api.rlaas.tech/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
