services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  redis_node_1:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_node_1_data:/data
    command: redis-server --appendonly yes

  redis_node_2:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_node_2_data:/data
    command: redis-server --appendonly yes

  redis_node_3:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - redis_node_3_data:/data
    command: redis-server --appendonly yes

volumes:
  psql_volume_bp:
  redis_node_1_data:
  redis_node_2_data:
  redis_node_3_data: